name: Process Transfers and Registrations
on:
  issues:
    types: [opened]

jobs:
  process:
    if: startsWith(github.event.issue.title, 'TRANSFER:') || startsWith(github.event.issue.title, 'REGISTER:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Process
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
import json, os, sys, requests

titulo = os.environ['ISSUE_TITLE']
partes = titulo.split(':')
tipo = partes[0]

users_file = 'users.json'
if os.path.exists(users_file):
    with open(users_file) as f:
        users = json.load(f)
else:
    users = {}

if tipo == 'REGISTER':
    # Formato: REGISTER:usuario:contraseña
    if len(partes) != 3:
        print('Formato de registro incorrecto')
        sys.exit(1)
    _, usuario, password = partes
    if usuario in users:
        comentario = '❌ El usuario ya existe'
    else:
        users[usuario] = {'password': password, 'saldoUSDT': 1000, 'btc': 0, 'tarjetas': []}
        comentario = f'✅ Usuario {usuario} registrado correctamente'
    # Guardar
    with open(users_file, 'w') as f:
        json.dump(users, f, indent=2)
    # Comentar en el issue
    url = f'https://api.github.com/repos/${{ github.repository }}/issues/{os.environ[\"ISSUE_NUMBER\"]}/comments'
    headers = {'Authorization': f'token {os.environ[\"GITHUB_TOKEN\"]}'}
    data = {'body': comentario}
    requests.post(url, json=data, headers=headers)

elif tipo == 'TRANSFER':
    # (código existente de transferencia)
    ...
"
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add users.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Process #${{ github.event.issue.number }} [skip ci]" && git push)

      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Procesado automáticamente.
